// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "gXQUv0P4a14dkBLmLRa0j25kvyOWOEieNrhAKsQxF8zrl8dcbPRUuZNp0r8z6EasmWnQ21";
}
}
}

